language: java
jdk: openjdk11
os: linux

services:
  - docker

install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/

stages:
  - build
  - quality assurance
  - release

jobs:
  include:
    - stage: build
      script: ./gradlew clean build -x test
    - stage: quality assurance
      script: ./gradlew test
    - stage: quality assurance
      script: ./gradlew detekt
    - stage: release
      script: ./gradlew docker
      if: branch = master